version: '2'
services:
   db:
     image: postgres
   static:
     build: nginx
     volumes:
       - ./static:/var/www/static
     ports:
       - "8001:8001"
     depends_on:
       - django
   django:
     build: django
     command: python manage.py runserver 0.0.0.0:8000
     volumes:
       - ./django:/code
     ports:
       - "8000:8000"
     depends_on:
       - db
